### ISSUE TITLE
`p-search` buffer name

### ISSUE THREAD

**Issue by swflint** [zkry/p-search#26]
Would it be possible to include a bit more information in the buffer name? E.g., the project or directory name (like Magit does), or generate the buffer name using, for example, `project-compilation-buffer-name-function`?

**Comment by zkry** [comment]
Great idea! This is a much needed feature thinking about it. I'll put this top on my things to do.

**Comment by zkry** [comment]
So an initial implementation for this is on the latest main.  I added a new property for each candidate generator called `lighter-function`, which lets the candidate generator return a string which describes the context of the search. 

So for example, adding a filesystem generator for the "/foo/bar/baz/" directory will have the `p-search-candidate-generator-filesystem` return "fs:baz/", which will then become part of the buffer name: "*p-search<fs:baz/>*" . If multiple generators exist, ellipsis is added: "*p-search<fs:baz/...>*"

I'm thinking about features regarding saved search sessions/templates, like if you have a predefined set of candidate generators (e.g. your notes directory) that you access often, and so maybe having a rename-session command would make sense.
