### ISSUE TITLE
Prompts for priors are missing a trailing space

### ISSUE THREAD

**Issue by swflint** [zkry/p-search#27]
Prompts for priors are missing a trailing space.  For example, see the attached image.
![1](https://github.com/user-attachments/assets/c112938c-93c9-404c-a0d5-a03178c07743)

Additionally, prompts are not the most descriptive, limiting discoverability

**Comment by zkry** [comment]
Good idea. I'm thinking about allowing for a description string to appear before the variable prompt. So in this case it would show a whole "cheat sheet" about how the querying system works.

**Comment by swflint** [comment]
It's definitely better now!

You may want to a) call it `p-search-expert-prompt` and have it set to nil by default (to follow some similar things from Org, b) make it a customizable variable, and c) provide the classes a way to specify a simple prompt string.

For example, `query-string` is not the most human-friendly prompt, but `Query String` would be.  If you are computing the prompt string yourself (haven't dug into the code fully yet), the `format-prompt` function would likely be helpful as well to ensure that there's a colon & space.

**Comment by zkry** [comment]
That's a good recommendation. It should be fairly simple to add like a display name. I'll work on this.

**Comment by swflint** [comment]
That's fantastic, thank you!
