### ISSUE TITLE
p-search and elpaca

### ISSUE THREAD

**Issue by djgoku** [zkry/p-search#35]
I am trying to use p-search and elpaca. So this could be an issue with elpaca. But with this minimal config after loading the config the screenshot is what I get.

[early-init.el.txt](https://github.com/user-attachments/files/18049384/early-init.el.txt)
[init.el.txt](https://github.com/user-attachments/files/18049407/init.el.txt)
![Screenshot 2024-12-07 at 12 11 24](https://github.com/user-attachments/assets/d42dd2a5-a288-490a-8df7-097f33d637a8)

**Comment by djgoku** [comment]
The behavior seems to be the same when using straight.el:

[init.el.txt](https://github.com/user-attachments/files/18049741/init.el.txt)
![Uploading Screenshot 2024-12-07 at 14.04.00.png…]()

**Comment by zkry** [comment]
my apologies. There appeared to an out of place piece of code. It shouldn't be doing this anymore.

**Comment by djgoku** [comment]
Thank you for the quick turnaround. Your emacs conf talk was awesome!
