### ISSUE TITLE
Multiple candidates from a single file

### ISSUE THREAD

**Issue by swflint** [zkry/p-search#45]
Based on the mappings proposal from #41 and some thoughts on how parts of #42 could work, would it be possible to implement a multiple-candidates-from-a-file sort of candidate generator?

**Comment by zkry** [comment]
Yeah, this is definitely possible! Here's an example of this I've added to the mapping PR: https://github.com/zkry/p-search/blob/implement-mappings/mappings/p-search-filesplit.el

Here you can see it's creating a lot of sub-documents by splitting up the larger files.

![Screenshot 2024-12-21 at 1 07 51 AM](https://github.com/user-attachments/assets/9740f3d1-65bd-4f3a-909b-948ac3cfba32)

**Comment by zkry** [comment]
psx-filesplit is merged in now in the extensions subdirectory as an example. There are some improvements I feel that could be made ti this mapping in particular (like having some overlap between segments), but this is probably less important.  There are also some other mappings on the roadmap like splitting a file into "defuns" (whatever the major mode defines them as).
