### ISSUE TITLE
Explain Score

### ISSUE THREAD

**Issue by swflint** [zkry/p-search#46]
Would it possible to add a "explain score" function?  For example if my point is on a result, I'd like to be able to press, e.g., `x`, and get an explanation of the score (what priors does it match, etc.).

**Comment by zkry** [comment]
This is a definitely something I feel is needed. So much so probably, I'll prioritize getting this done before its first official release.

**Comment by zkry** [comment]
There should now be an new command called `p-search-explain-dwim` (bound by default to `x`) which displays a buffer with information regarding the result at point. Down the line I hope to make it able to explain the other entities in the system.

<img width="684" alt="Screenshot 2024-12-22 at 11 22 42 PM" src="https://github.com/user-attachments/assets/8d60f822-4805-496d-b22b-70054d22931a" />
