### ISSUE TITLE
Show More Results/paginate results

### ISSUE THREAD

**Issue by swflint** [zkry/p-search#47]
Would it be possible to add a binding to show more results (next `p-search-top-n`?), or add support for pagination of results?

**Comment by zkry** [comment]
Definitely, this should be fairly simple to implement.

**Comment by zkry** [comment]
Two new commands, p-search-prev-results-page and p-search-next-results-page (bound to "<" and ">" by default) should now be available to navigate search result pages.

**Comment by swflint** [comment]
Thank you!
